Update sprayer-custom-v1.yml

diff --git a/.github/workflows/sprayer-custom-v1.yml b/.github/workflows/sprayer-custom-v1.yml
--- a/.github/workflows/sprayer-custom-v1.yml
+++ b/.github/workflows/sprayer-custom-v1.yml
@@ -31,7 +31,11 @@ jobs:
           echo "[+] Proxy Thermoptic iniciado"
           docker compose ps
           sleep 15
-          curl --proxy http://changeme:changeme@127.0.0.1:1234 --insecure https://ja4db.com/id/ja4h/ || echo "curl ja4 failed"
+          echo "insecure and proxied"
+          curl --proxy http://changeme:changeme@127.0.0.1:1234 --insecure https://ja4db.com/id/ja4h/ || echo "curl insecure proxied failed"
+          echo "proxied"
+          curl --proxy http://changeme:changeme@127.0.0.1:1234 https://ja4db.com/id/ja4h/ || echo "curl ja4 failed"
+          echo "normal"
           curl  https://ja4db.com/id/ja4h/ || echo "curl ja4 failed"
       
       - name: Run Sprayer
